import { Product } from './types';

export const products: Product[] = [
  {
    id: 'prod_1',
    name: 'Wireless Headphones',
    description: 'High-quality wireless headphones with great features and excellent durability',
    price: 20.00,
    category: 'Electronics',
    image: '/products/headphones.jpg',
    stock: 75,
    rating: 4.0,
    reviewCount: 441,
  },
  {
    id: 'prod_2',
    name: 'Smart Watch',
    description: 'High-quality smart watch with great features and excellent durability',
    price: 22.50,
    category: 'Electronics',
    image: '/products/smartwatch.jpg',
    stock: 39,
    rating: 4.2,
    reviewCount: 375,
  },
  {
    id: 'prod_3',
    name: 'USB-C Cable',
    description: 'High-quality usb-c cable with great features and excellent durability',
    price: 25.00,
    category: 'Electronics',
    image: '/products/cable.jpg',
    stock: 67,
    rating: 4.2,
    reviewCount: 149,
  },
  {
    id: 'prod_4',
    name: 'Phone Stand',
    description: 'High-quality phone stand with great features and excellent durability',
    price: 27.50,
    category: 'Electronics',
    image: '/products/stand.jpg',
    stock: 60,
    rating: 4.4,
    reviewCount: 263,
  },
  {
    id: 'prod_5',
    name: 'Portable Charger',
    description: 'High-quality portable charger with great features and excellent durability',
    price: 30.00,
    category: 'Electronics',
    image: '/products/powerbank.jpg',
    stock: 28,
    rating: 4.1,
    reviewCount: 451,
  },
  {
    id: 'prod_6',
    name: 'Webcam HD',
    description: 'High-quality webcam hd with great features and excellent durability',
    price: 32.50,
    category: 'Electronics',
    image: '/products/webcam.jpg',
    stock: 51,
    rating: 4.4,
    reviewCount: 167,
  },
  {
    id: 'prod_7',
    name: 'Mechanical Keyboard',
    description: 'High-quality mechanical keyboard with great features and excellent durability',
    price: 35.00,
    category: 'Electronics',
    image: '/products/keyboard.jpg',
    stock: 78,
    rating: 4.7,
    reviewCount: 160,
  },
  {
    id: 'prod_8',
    name: 'Gaming Mouse Pad',
    description: 'High-quality gaming mouse pad with great features and excellent durability',
    price: 37.50,
    category: 'Electronics',
    image: '/products/mouse.jpg',
    stock: 79,
    rating: 4.4,
    reviewCount: 142,
  },
  {
    id: 'prod_9',
    name: 'Laptop Stand',
    description: 'High-quality laptop stand with great features and excellent durability',
    price: 40.00,
    category: 'Electronics',
    image: '/products/stand.jpg',
    stock: 72,
    rating: 4.4,
    reviewCount: 476,
  },
  {
    id: 'prod_10',
    name: 'Wireless Mouse',
    description: 'High-quality wireless mouse with great features and excellent durability',
    price: 42.50,
    category: 'Electronics',
    image: '/products/mouse.jpg',
    stock: 70,
    rating: 4.2,
    reviewCount: 486,
  },
  {
    id: 'prod_11',
    name: 'USB Hub',
    description: 'High-quality usb hub with great features and excellent durability',
    price: 45.00,
    category: 'Electronics',
    image: '/products/cable.jpg',
    stock: 111,
    rating: 4.5,
    reviewCount: 318,
  },
  {
    id: 'prod_12',
    name: 'External SSD',
    description: 'High-quality external ssd with great features and excellent durability',
    price: 47.50,
    category: 'Electronics',
    image: '/products/powerbank.jpg',
    stock: 104,
    rating: 4.4,
    reviewCount: 237,
  },
  {
    id: 'prod_13',
    name: 'Monitor Light',
    description: 'High-quality monitor light with great features and excellent durability',
    price: 50.00,
    category: 'Electronics',
    image: '/products/lamp.jpg',
    stock: 57,
    rating: 4.2,
    reviewCount: 200,
  },
  {
    id: 'prod_14',
    name: 'Cable Organizer',
    description: 'High-quality cable organizer with great features and excellent durability',
    price: 52.50,
    category: 'Electronics',
    image: '/products/cable.jpg',
    stock: 75,
    rating: 4.8,
    reviewCount: 324,
  },
  {
    id: 'prod_15',
    name: 'Screen Protector',
    description: 'High-quality screen protector with great features and excellent durability',
    price: 55.00,
    category: 'Electronics',
    image: '/products/smartphone.jpg',
    stock: 111,
    rating: 4.1,
    reviewCount: 278,
  },
  {
    id: 'prod_16',
    name: 'Phone Case',
    description: 'High-quality phone case with great features and excellent durability',
    price: 57.50,
    category: 'Electronics',
    image: '/products/tshirt.jpg',
    stock: 46,
    rating: 4.0,
    reviewCount: 106,
  },
  {
    id: 'prod_17',
    name: 'Car Charger',
    description: 'High-quality car charger with great features and excellent durability',
    price: 60.00,
    category: 'Electronics',
    image: '/products/powerbank.jpg',
    stock: 45,
    rating: 4.1,
    reviewCount: 53,
  },
  {
    id: 'prod_18',
    name: 'Bluetooth Speaker',
    description: 'High-quality bluetooth speaker with great features and excellent durability',
    price: 62.50,
    category: 'Electronics',
    image: '/products/speaker.jpg',
    stock: 69,
    rating: 4.7,
    reviewCount: 59,
  },
  {
    id: 'prod_19',
    name: 'Thermal Camera',
    description: 'High-quality thermal camera with great features and excellent durability',
    price: 65.00,
    category: 'Electronics',
    image: '/products/webcam.jpg',
    stock: 67,
    rating: 4.3,
    reviewCount: 251,
  },
  {
    id: 'prod_20',
    name: 'WiFi Router',
    description: 'High-quality wifi router with great features and excellent durability',
    price: 67.50,
    category: 'Electronics',
    image: '/products/router.jpg',
    stock: 38,
    rating: 4.4,
    reviewCount: 233,
  },
  {
    id: 'prod_21',
    name: 'Power Bank XL',
    description: 'High-quality power bank xl with great features and excellent durability',
    price: 70.00,
    category: 'Electronics',
    image: '/products/powerbank.jpg',
    stock: 29,
    rating: 4.6,
    reviewCount: 470,
  },
  {
    id: 'prod_22',
    name: 'Lightning Cable',
    description: 'High-quality lightning cable with great features and excellent durability',
    price: 72.50,
    category: 'Electronics',
    image: '/products/cable.jpg',
    stock: 68,
    rating: 4.0,
    reviewCount: 237,
  },
  {
    id: 'prod_23',
    name: 'HDMI Cable',
    description: 'High-quality hdmi cable with great features and excellent durability',
    price: 75.00,
    category: 'Electronics',
    image: '/products/cable.jpg',
    stock: 114,
    rating: 4.0,
    reviewCount: 257,
  },
  {
    id: 'prod_24',
    name: 'Desk Lamp LED',
    description: 'High-quality desk lamp led with great features and excellent durability',
    price: 77.50,
    category: 'Electronics',
    image: '/products/lamp.jpg',
    stock: 88,
    rating: 4.2,
    reviewCount: 389,
  },
  {
    id: 'prod_25',
    name: 'Phone Tripod',
    description: 'High-quality phone tripod with great features and excellent durability',
    price: 80.00,
    category: 'Electronics',
    image: '/products/stand.jpg',
    stock: 105,
    rating: 4.7,
    reviewCount: 269,
  },
  {
    id: 'prod_26',
    name: 'Microphone Condenser',
    description: 'High-quality microphone condenser with great features and excellent durability',
    price: 82.50,
    category: 'Electronics',
    image: '/products/webcam.jpg',
    stock: 85,
    rating: 4.7,
    reviewCount: 332,
  },
  {
    id: 'prod_27',
    name: 'Mini Projector',
    description: 'High-quality mini projector with great features and excellent durability',
    price: 85.00,
    category: 'Electronics',
    image: '/products/router.jpg',
    stock: 101,
    rating: 4.6,
    reviewCount: 315,
  },
  {
    id: 'prod_28',
    name: 'Digital Thermometer',
    description: 'High-quality digital thermometer with great features and excellent durability',
    price: 87.50,
    category: 'Electronics',
    image: '/products/deodorant.jpg',
    stock: 68,
    rating: 4.6,
    reviewCount: 358,
  },
  {
    id: 'prod_29',
    name: 'Dash Cam',
    description: 'High-quality dash cam with great features and excellent durability',
    price: 90.00,
    category: 'Electronics',
    image: '/products/webcam.jpg',
    stock: 53,
    rating: 4.1,
    reviewCount: 426,
  },
  {
    id: 'prod_30',
    name: 'Ring Light',
    description: 'High-quality ring light with great features and excellent durability',
    price: 92.50,
    category: 'Electronics',
    image: '/products/lamp.jpg',
    stock: 78,
    rating: 4.1,
    reviewCount: 379,
  },
  {
    id: 'prod_31',
    name: 'Mens Cotton Shirt',
    description: 'High-quality mens cotton shirt with great features and excellent durability',
    price: 20.00,
    category: 'Clothing',
    image: '/products/tshirt.jpg',
    stock: 83,
    rating: 4.3,
    reviewCount: 281,
  },
  {
    id: 'prod_32',
    name: 'Classic Blue Jeans',
    description: 'High-quality classic blue jeans with great features and excellent durability',
    price: 22.50,
    category: 'Clothing',
    image: '/products/jeans.jpg',
    stock: 64,
    rating: 4.4,
    reviewCount: 261,
  },
  {
    id: 'prod_33',
    name: 'Leather Jacket',
    description: 'High-quality leather jacket with great features and excellent durability',
    price: 25.00,
    category: 'Clothing',
    image: '/products/jacket.jpg',
    stock: 100,
    rating: 4.6,
    reviewCount: 58,
  },
  {
    id: 'prod_34',
    name: 'White Athletic Sneakers',
    description: 'High-quality white athletic sneakers with great features and excellent durability',
    price: 27.50,
    category: 'Clothing',
    image: '/products/sneakers.jpg',
    stock: 97,
    rating: 4.2,
    reviewCount: 213,
  },
  {
    id: 'prod_35',
    name: 'Black T-Shirt',
    description: 'High-quality black t-shirt with great features and excellent durability',
    price: 30.00,
    category: 'Clothing',
    image: '/products/tshirt.jpg',
    stock: 24,
    rating: 4.4,
    reviewCount: 220,
  },
  {
    id: 'prod_36',
    name: 'Gray Hoodie',
    description: 'High-quality gray hoodie with great features and excellent durability',
    price: 32.50,
    category: 'Clothing',
    image: '/products/hoodie.jpg',
    stock: 88,
    rating: 4.8,
    reviewCount: 462,
  },
  {
    id: 'prod_37',
    name: 'Denim Shorts',
    description: 'High-quality denim shorts with great features and excellent durability',
    price: 35.00,
    category: 'Clothing',
    image: '/products/jeans.jpg',
    stock: 35,
    rating: 4.7,
    reviewCount: 289,
  },
  {
    id: 'prod_38',
    name: 'Casual Blazer',
    description: 'High-quality casual blazer with great features and excellent durability',
    price: 37.50,
    category: 'Clothing',
    image: '/products/jacket.jpg',
    stock: 75,
    rating: 4.3,
    reviewCount: 268,
  },
  {
    id: 'prod_39',
    name: 'Wool Sweater',
    description: 'High-quality wool sweater with great features and excellent durability',
    price: 40.00,
    category: 'Clothing',
    image: '/products/hoodie.jpg',
    stock: 39,
    rating: 4.2,
    reviewCount: 493,
  },
  {
    id: 'prod_40',
    name: 'Khaki Pants',
    description: 'High-quality khaki pants with great features and excellent durability',
    price: 42.50,
    category: 'Clothing',
    image: '/products/jeans.jpg',
    stock: 31,
    rating: 4.3,
    reviewCount: 66,
  },
  {
    id: 'prod_41',
    name: 'Running Shoes',
    description: 'High-quality running shoes with great features and excellent durability',
    price: 45.00,
    category: 'Clothing',
    image: '/products/runningshoes.jpg',
    stock: 90,
    rating: 4.1,
    reviewCount: 303,
  },
  {
    id: 'prod_42',
    name: 'Summer Dress',
    description: 'High-quality summer dress with great features and excellent durability',
    price: 47.50,
    category: 'Clothing',
    image: '/products/dress.jpg',
    stock: 42,
    rating: 4.1,
    reviewCount: 69,
  },
  {
    id: 'prod_43',
    name: 'Denim Vest',
    description: 'High-quality denim vest with great features and excellent durability',
    price: 50.00,
    category: 'Clothing',
    image: '/products/jacket.jpg',
    stock: 40,
    rating: 4.5,
    reviewCount: 68,
  },
  {
    id: 'prod_44',
    name: 'Polo Shirt',
    description: 'High-quality polo shirt with great features and excellent durability',
    price: 52.50,
    category: 'Clothing',
    image: '/products/tshirt.jpg',
    stock: 71,
    rating: 4.3,
    reviewCount: 445,
  },
  {
    id: 'prod_45',
    name: 'Winter Coat',
    description: 'High-quality winter coat with great features and excellent durability',
    price: 55.00,
    category: 'Clothing',
    image: '/products/jacket.jpg',
    stock: 57,
    rating: 4.3,
    reviewCount: 463,
  },
  {
    id: 'prod_46',
    name: 'Dress Pants',
    description: 'High-quality dress pants with great features and excellent durability',
    price: 57.50,
    category: 'Clothing',
    image: '/products/jeans.jpg',
    stock: 51,
    rating: 4.4,
    reviewCount: 179,
  },
  {
    id: 'prod_47',
    name: 'Tank Top',
    description: 'High-quality tank top with great features and excellent durability',
    price: 60.00,
    category: 'Clothing',
    image: '/products/tshirt.jpg',
    stock: 71,
    rating: 4.4,
    reviewCount: 130,
  },
  {
    id: 'prod_48',
    name: 'Long Sleeve Shirt',
    description: 'High-quality long sleeve shirt with great features and excellent durability',
    price: 62.50,
    category: 'Clothing',
    image: '/products/tshirt.jpg',
    stock: 101,
    rating: 4.6,
    reviewCount: 383,
  },
  {
    id: 'prod_49',
    name: 'Cargo Pants',
    description: 'High-quality cargo pants with great features and excellent durability',
    price: 65.00,
    category: 'Clothing',
    image: '/products/jeans.jpg',
    stock: 84,
    rating: 4.7,
    reviewCount: 73,
  },
  {
    id: 'prod_50',
    name: 'Cardigan Sweater',
    description: 'High-quality cardigan sweater with great features and excellent durability',
    price: 67.50,
    category: 'Clothing',
    image: '/products/hoodie.jpg',
    stock: 29,
    rating: 4.2,
    reviewCount: 389,
  },
  {
    id: 'prod_51',
    name: 'Swim Trunks',
    description: 'High-quality swim trunks with great features and excellent durability',
    price: 70.00,
    category: 'Clothing',
    image: '/products/jeans.jpg',
    stock: 93,
    rating: 4.8,
    reviewCount: 302,
  },
  {
    id: 'prod_52',
    name: 'Skirt',
    description: 'High-quality skirt with great features and excellent durability',
    price: 72.50,
    category: 'Clothing',
    image: '/products/dress.jpg',
    stock: 108,
    rating: 4.4,
    reviewCount: 230,
  },
  {
    id: 'prod_53',
    name: 'Jacket Puffer',
    description: 'High-quality jacket puffer with great features and excellent durability',
    price: 75.00,
    category: 'Clothing',
    image: '/products/jacket.jpg',
    stock: 81,
    rating: 4.5,
    reviewCount: 371,
  },
  {
    id: 'prod_54',
    name: 'Formal Shirt',
    description: 'High-quality formal shirt with great features and excellent durability',
    price: 77.50,
    category: 'Clothing',
    image: '/products/tshirt.jpg',
    stock: 97,
    rating: 4.3,
    reviewCount: 323,
  },
  {
    id: 'prod_55',
    name: 'Joggers',
    description: 'High-quality joggers with great features and excellent durability',
    price: 80.00,
    category: 'Clothing',
    image: '/products/hoodie.jpg',
    stock: 36,
    rating: 4.1,
    reviewCount: 142,
  },
  {
    id: 'prod_56',
    name: 'Leather Belt',
    description: 'High-quality leather belt with great features and excellent durability',
    price: 82.50,
    category: 'Clothing',
    image: '/products/jacket.jpg',
    stock: 52,
    rating: 4.4,
    reviewCount: 377,
  },
  {
    id: 'prod_57',
    name: 'Linen Shirt',
    description: 'High-quality linen shirt with great features and excellent durability',
    price: 85.00,
    category: 'Clothing',
    image: '/products/tshirt.jpg',
    stock: 107,
    rating: 4.4,
    reviewCount: 108,
  },
  {
    id: 'prod_58',
    name: 'Capri Pants',
    description: 'High-quality capri pants with great features and excellent durability',
    price: 87.50,
    category: 'Clothing',
    image: '/products/jeans.jpg',
    stock: 110,
    rating: 4.1,
    reviewCount: 104,
  },
  {
    id: 'prod_59',
    name: 'Crew Neck Sweater',
    description: 'High-quality crew neck sweater with great features and excellent durability',
    price: 90.00,
    category: 'Clothing',
    image: '/products/hoodie.jpg',
    stock: 89,
    rating: 4.5,
    reviewCount: 477,
  },
  {
    id: 'prod_60',
    name: 'Oxford Shoes',
    description: 'High-quality oxford shoes with great features and excellent durability',
    price: 92.50,
    category: 'Clothing',
    image: '/products/sneakers.jpg',
    stock: 39,
    rating: 4.4,
    reviewCount: 204,
  },
  {
    id: 'prod_61',
    name: 'Fiction Novel Bestseller',
    description: 'High-quality fiction novel bestseller with great features and excellent durability',
    price: 20.00,
    category: 'Books',
    image: '/products/novel.jpg',
    stock: 76,
    rating: 4.2,
    reviewCount: 221,
  },
  {
    id: 'prod_62',
    name: 'Professional Cookbook',
    description: 'High-quality professional cookbook with great features and excellent durability',
    price: 22.50,
    category: 'Books',
    image: '/products/cookbook.jpg',
    stock: 25,
    rating: 4.5,
    reviewCount: 210,
  },
  {
    id: 'prod_63',
    name: 'Science Discovery',
    description: 'High-quality science discovery with great features and excellent durability',
    price: 25.00,
    category: 'Books',
    image: '/products/novel.jpg',
    stock: 98,
    rating: 4.8,
    reviewCount: 499,
  },
  {
    id: 'prod_64',
    name: 'Mystery Thriller',
    description: 'High-quality mystery thriller with great features and excellent durability',
    price: 27.50,
    category: 'Books',
    image: '/products/novel.jpg',
    stock: 48,
    rating: 4.5,
    reviewCount: 369,
  },
  {
    id: 'prod_65',
    name: 'Romance Novel',
    description: 'High-quality romance novel with great features and excellent durability',
    price: 30.00,
    category: 'Books',
    image: '/products/novel.jpg',
    stock: 26,
    rating: 4.0,
    reviewCount: 472,
  },
  {
    id: 'prod_66',
    name: 'Self-Help Guide',
    description: 'High-quality self-help guide with great features and excellent durability',
    price: 32.50,
    category: 'Books',
    image: '/products/selfhelp.jpg',
    stock: 72,
    rating: 4.7,
    reviewCount: 137,
  },
  {
    id: 'prod_67',
    name: 'Biography Classic',
    description: 'High-quality biography classic with great features and excellent durability',
    price: 35.00,
    category: 'Books',
    image: '/products/novel.jpg',
    stock: 58,
    rating: 4.2,
    reviewCount: 395,
  },
  {
    id: 'prod_68',
    name: 'Fantasy Adventure',
    description: 'High-quality fantasy adventure with great features and excellent durability',
    price: 37.50,
    category: 'Books',
    image: '/products/novel.jpg',
    stock: 113,
    rating: 4.3,
    reviewCount: 496,
  },
  {
    id: 'prod_69',
    name: 'Sci-Fi Future',
    description: 'High-quality sci-fi future with great features and excellent durability',
    price: 40.00,
    category: 'Books',
    image: '/products/novel.jpg',
    stock: 71,
    rating: 4.7,
    reviewCount: 121,
  },
  {
    id: 'prod_70',
    name: 'Poetry Collection',
    description: 'High-quality poetry collection with great features and excellent durability',
    price: 42.50,
    category: 'Books',
    image: '/products/novel.jpg',
    stock: 23,
    rating: 4.1,
    reviewCount: 94,
  },
  {
    id: 'prod_71',
    name: 'History Documentary',
    description: 'High-quality history documentary with great features and excellent durability',
    price: 45.00,
    category: 'Books',
    image: '/products/novel.jpg',
    stock: 86,
    rating: 4.0,
    reviewCount: 392,
  },
  {
    id: 'prod_72',
    name: 'Business Strategy',
    description: 'High-quality business strategy with great features and excellent durability',
    price: 47.50,
    category: 'Books',
    image: '/products/selfhelp.jpg',
    stock: 101,
    rating: 4.1,
    reviewCount: 388,
  },
  {
    id: 'prod_73',
    name: 'Art Coffee Table',
    description: 'High-quality art coffee table with great features and excellent durability',
    price: 50.00,
    category: 'Books',
    image: '/products/novel.jpg',
    stock: 95,
    rating: 4.2,
    reviewCount: 180,
  },
  {
    id: 'prod_74',
    name: 'Graphic Novel',
    description: 'High-quality graphic novel with great features and excellent durability',
    price: 52.50,
    category: 'Books',
    image: '/products/novel.jpg',
    stock: 59,
    rating: 4.8,
    reviewCount: 103,
  },
  {
    id: 'prod_75',
    name: 'Young Adult Series',
    description: 'High-quality young adult series with great features and excellent durability',
    price: 55.00,
    category: 'Books',
    image: '/products/novel.jpg',
    stock: 103,
    rating: 4.7,
    reviewCount: 398,
  },
  {
    id: 'prod_76',
    name: 'Philosophy Deep',
    description: 'High-quality philosophy deep with great features and excellent durability',
    price: 57.50,
    category: 'Books',
    image: '/products/selfhelp.jpg',
    stock: 76,
    rating: 4.8,
    reviewCount: 470,
  },
  {
    id: 'prod_77',
    name: 'Psychology Mind',
    description: 'High-quality psychology mind with great features and excellent durability',
    price: 60.00,
    category: 'Books',
    image: '/products/selfhelp.jpg',
    stock: 28,
    rating: 4.2,
    reviewCount: 353,
  },
  {
    id: 'prod_78',
    name: 'Travel Guide',
    description: 'High-quality travel guide with great features and excellent durability',
    price: 62.50,
    category: 'Books',
    image: '/products/novel.jpg',
    stock: 70,
    rating: 4.5,
    reviewCount: 198,
  },
  {
    id: 'prod_79',
    name: 'Cooking Authentic',
    description: 'High-quality cooking authentic with great features and excellent durability',
    price: 65.00,
    category: 'Books',
    image: '/products/cookbook.jpg',
    stock: 37,
    rating: 4.1,
    reviewCount: 462,
  },
  {
    id: 'prod_80',
    name: 'Fitness Training',
    description: 'High-quality fitness training with great features and excellent durability',
    price: 67.50,
    category: 'Books',
    image: '/products/selfhelp.jpg',
    stock: 116,
    rating: 4.2,
    reviewCount: 424,
  },
  {
    id: 'prod_81',
    name: 'Mindfulness Wellness',
    description: 'High-quality mindfulness wellness with great features and excellent durability',
    price: 70.00,
    category: 'Books',
    image: '/products/selfhelp.jpg',
    stock: 85,
    rating: 4.7,
    reviewCount: 61,
  },
  {
    id: 'prod_82',
    name: 'True Crime',
    description: 'High-quality true crime with great features and excellent durability',
    price: 72.50,
    category: 'Books',
    image: '/products/novel.jpg',
    stock: 105,
    rating: 4.2,
    reviewCount: 347,
  },
  {
    id: 'prod_83',
    name: 'Historical Fiction',
    description: 'High-quality historical fiction with great features and excellent durability',
    price: 75.00,
    category: 'Books',
    image: '/products/novel.jpg',
    stock: 69,
    rating: 4.3,
    reviewCount: 231,
  },
  {
    id: 'prod_84',
    name: 'Children Stories',
    description: 'High-quality children stories with great features and excellent durability',
    price: 77.50,
    category: 'Books',
    image: '/products/novel.jpg',
    stock: 71,
    rating: 4.3,
    reviewCount: 294,
  },
  {
    id: 'prod_85',
    name: 'Technical Guide',
    description: 'High-quality technical guide with great features and excellent durability',
    price: 80.00,
    category: 'Books',
    image: '/products/selfhelp.jpg',
    stock: 73,
    rating: 4.6,
    reviewCount: 335,
  },
  {
    id: 'prod_86',
    name: 'Memoir Personal',
    description: 'High-quality memoir personal with great features and excellent durability',
    price: 82.50,
    category: 'Books',
    image: '/products/novel.jpg',
    stock: 83,
    rating: 4.3,
    reviewCount: 378,
  },
  {
    id: 'prod_87',
    name: 'Comedy Humor',
    description: 'High-quality comedy humor with great features and excellent durability',
    price: 85.00,
    category: 'Books',
    image: '/products/novel.jpg',
    stock: 92,
    rating: 4.5,
    reviewCount: 492,
  },
  {
    id: 'prod_88',
    name: 'Action Adventure',
    description: 'High-quality action adventure with great features and excellent durability',
    price: 87.50,
    category: 'Books',
    image: '/products/novel.jpg',
    stock: 118,
    rating: 4.5,
    reviewCount: 407,
  },
  {
    id: 'prod_89',
    name: 'Detective Mystery',
    description: 'High-quality detective mystery with great features and excellent durability',
    price: 90.00,
    category: 'Books',
    image: '/products/novel.jpg',
    stock: 41,
    rating: 4.6,
    reviewCount: 188,
  },
  {
    id: 'prod_90',
    name: 'Educational Learn',
    description: 'High-quality educational learn with great features and excellent durability',
    price: 92.50,
    category: 'Books',
    image: '/products/novel.jpg',
    stock: 104,
    rating: 4.6,
    reviewCount: 203,
  },
  {
    id: 'prod_91',
    name: 'Modern LED Desk Lamp',
    description: 'High-quality modern led desk lamp with great features and excellent durability',
    price: 20.00,
    category: 'Home & Garden',
    image: '/products/lamp.jpg',
    stock: 76,
    rating: 4.7,
    reviewCount: 360,
  },
  {
    id: 'prod_92',
    name: 'Cotton Bed Sheets Set',
    description: 'High-quality cotton bed sheets set with great features and excellent durability',
    price: 22.50,
    category: 'Home & Garden',
    image: '/products/bedding.jpg',
    stock: 102,
    rating: 4.4,
    reviewCount: 306,
  },
  {
    id: 'prod_93',
    name: 'Indoor Plant Potted',
    description: 'High-quality indoor plant potted with great features and excellent durability',
    price: 25.00,
    category: 'Home & Garden',
    image: '/products/plant.jpg',
    stock: 47,
    rating: 4.6,
    reviewCount: 293,
  },
  {
    id: 'prod_94',
    name: 'Decorative Pillow',
    description: 'High-quality decorative pillow with great features and excellent durability',
    price: 27.50,
    category: 'Home & Garden',
    image: '/products/pillow.jpg',
    stock: 99,
    rating: 4.5,
    reviewCount: 413,
  },
  {
    id: 'prod_95',
    name: 'Wall Mirror',
    description: 'High-quality wall mirror with great features and excellent durability',
    price: 30.00,
    category: 'Home & Garden',
    image: '/products/mirror.jpg',
    stock: 93,
    rating: 4.3,
    reviewCount: 416,
  },
  {
    id: 'prod_96',
    name: 'Coffee Table Wood',
    description: 'High-quality coffee table wood with great features and excellent durability',
    price: 32.50,
    category: 'Home & Garden',
    image: '/products/bedding.jpg',
    stock: 113,
    rating: 4.7,
    reviewCount: 421,
  },
  {
    id: 'prod_97',
    name: 'Throw Blanket',
    description: 'High-quality throw blanket with great features and excellent durability',
    price: 35.00,
    category: 'Home & Garden',
    image: '/products/bedding.jpg',
    stock: 93,
    rating: 4.6,
    reviewCount: 230,
  },
  {
    id: 'prod_98',
    name: 'Desk Organizer',
    description: 'High-quality desk organizer with great features and excellent durability',
    price: 37.50,
    category: 'Home & Garden',
    image: '/products/mirror.jpg',
    stock: 36,
    rating: 4.3,
    reviewCount: 493,
  },
  {
    id: 'prod_99',
    name: 'Wall Shelf',
    description: 'High-quality wall shelf with great features and excellent durability',
    price: 40.00,
    category: 'Home & Garden',
    image: '/products/mirror.jpg',
    stock: 42,
    rating: 4.1,
    reviewCount: 198,
  },
  {
    id: 'prod_100',
    name: 'Curtain Rod',
    description: 'High-quality curtain rod with great features and excellent durability',
    price: 42.50,
    category: 'Home & Garden',
    image: '/products/pillow.jpg',
    stock: 103,
    rating: 4.3,
    reviewCount: 187,
  },
  {
    id: 'prod_101',
    name: 'Area Rug',
    description: 'High-quality area rug with great features and excellent durability',
    price: 45.00,
    category: 'Home & Garden',
    image: '/products/bedding.jpg',
    stock: 84,
    rating: 4.7,
    reviewCount: 447,
  },
  {
    id: 'prod_102',
    name: 'Picture Frame',
    description: 'High-quality picture frame with great features and excellent durability',
    price: 47.50,
    category: 'Home & Garden',
    image: '/products/mirror.jpg',
    stock: 110,
    rating: 4.2,
    reviewCount: 225,
  },
  {
    id: 'prod_103',
    name: 'Storage Basket',
    description: 'High-quality storage basket with great features and excellent durability',
    price: 50.00,
    category: 'Home & Garden',
    image: '/products/pillow.jpg',
    stock: 82,
    rating: 4.4,
    reviewCount: 101,
  },
  {
    id: 'prod_104',
    name: 'Outdoor Chair',
    description: 'High-quality outdoor chair with great features and excellent durability',
    price: 52.50,
    category: 'Home & Garden',
    image: '/products/bedding.jpg',
    stock: 92,
    rating: 4.7,
    reviewCount: 491,
  },
  {
    id: 'prod_105',
    name: 'Plant Pot Ceramic',
    description: 'High-quality plant pot ceramic with great features and excellent durability',
    price: 55.00,
    category: 'Home & Garden',
    image: '/products/plant.jpg',
    stock: 81,
    rating: 4.7,
    reviewCount: 395,
  },
  {
    id: 'prod_106',
    name: 'Tablecloth',
    description: 'High-quality tablecloth with great features and excellent durability',
    price: 57.50,
    category: 'Home & Garden',
    image: '/products/bedding.jpg',
    stock: 71,
    rating: 4.5,
    reviewCount: 415,
  },
  {
    id: 'prod_107',
    name: 'Cushion Seat',
    description: 'High-quality cushion seat with great features and excellent durability',
    price: 60.00,
    category: 'Home & Garden',
    image: '/products/pillow.jpg',
    stock: 79,
    rating: 4.1,
    reviewCount: 474,
  },
  {
    id: 'prod_108',
    name: 'Wall Decal',
    description: 'High-quality wall decal with great features and excellent durability',
    price: 62.50,
    category: 'Home & Garden',
    image: '/products/mirror.jpg',
    stock: 71,
    rating: 4.0,
    reviewCount: 426,
  },
  {
    id: 'prod_109',
    name: 'Lamp Shade',
    description: 'High-quality lamp shade with great features and excellent durability',
    price: 65.00,
    category: 'Home & Garden',
    image: '/products/lamp.jpg',
    stock: 73,
    rating: 4.7,
    reviewCount: 118,
  },
  {
    id: 'prod_110',
    name: 'Couch Throw',
    description: 'High-quality couch throw with great features and excellent durability',
    price: 67.50,
    category: 'Home & Garden',
    image: '/products/bedding.jpg',
    stock: 26,
    rating: 4.2,
    reviewCount: 336,
  },
  {
    id: 'prod_111',
    name: 'Door Mat',
    description: 'High-quality door mat with great features and excellent durability',
    price: 70.00,
    category: 'Home & Garden',
    image: '/products/pillow.jpg',
    stock: 41,
    rating: 4.8,
    reviewCount: 60,
  },
  {
    id: 'prod_112',
    name: 'Wall Clock',
    description: 'High-quality wall clock with great features and excellent durability',
    price: 72.50,
    category: 'Home & Garden',
    image: '/products/mirror.jpg',
    stock: 109,
    rating: 4.3,
    reviewCount: 318,
  },
  {
    id: 'prod_113',
    name: 'Shelf Brackets',
    description: 'High-quality shelf brackets with great features and excellent durability',
    price: 75.00,
    category: 'Home & Garden',
    image: '/products/mirror.jpg',
    stock: 25,
    rating: 4.4,
    reviewCount: 120,
  },
  {
    id: 'prod_114',
    name: 'Vase Glass',
    description: 'High-quality vase glass with great features and excellent durability',
    price: 77.50,
    category: 'Home & Garden',
    image: '/products/glass.jpg',
    stock: 77,
    rating: 4.5,
    reviewCount: 345,
  },
  {
    id: 'prod_115',
    name: 'Candle Holder',
    description: 'High-quality candle holder with great features and excellent durability',
    price: 80.00,
    category: 'Home & Garden',
    image: '/products/lamp.jpg',
    stock: 68,
    rating: 4.4,
    reviewCount: 206,
  },
  {
    id: 'prod_116',
    name: 'Bookshelf',
    description: 'High-quality bookshelf with great features and excellent durability',
    price: 82.50,
    category: 'Home & Garden',
    image: '/products/bedding.jpg',
    stock: 88,
    rating: 4.6,
    reviewCount: 417,
  },
  {
    id: 'prod_117',
    name: 'Ottoman Storage',
    description: 'High-quality ottoman storage with great features and excellent durability',
    price: 85.00,
    category: 'Home & Garden',
    image: '/products/pillow.jpg',
    stock: 62,
    rating: 4.4,
    reviewCount: 383,
  },
  {
    id: 'prod_118',
    name: 'Fabric Sofa',
    description: 'High-quality fabric sofa with great features and excellent durability',
    price: 87.50,
    category: 'Home & Garden',
    image: '/products/bedding.jpg',
    stock: 79,
    rating: 4.1,
    reviewCount: 107,
  },
  {
    id: 'prod_119',
    name: 'Garden Stake',
    description: 'High-quality garden stake with great features and excellent durability',
    price: 90.00,
    category: 'Home & Garden',
    image: '/products/plant.jpg',
    stock: 94,
    rating: 4.5,
    reviewCount: 158,
  },
  {
    id: 'prod_120',
    name: 'Hanging Planter',
    description: 'High-quality hanging planter with great features and excellent durability',
    price: 92.50,
    category: 'Home & Garden',
    image: '/products/plant.jpg',
    stock: 38,
    rating: 4.3,
    reviewCount: 394,
  },
  {
    id: 'prod_121',
    name: 'Dumbbell Set',
    description: 'High-quality dumbbell set with great features and excellent durability',
    price: 20.00,
    category: 'Sports & Outdoors',
    image: '/products/dumbbells.jpg',
    stock: 74,
    rating: 4.3,
    reviewCount: 151,
  },
  {
    id: 'prod_122',
    name: 'Purple Yoga Mat',
    description: 'High-quality purple yoga mat with great features and excellent durability',
    price: 22.50,
    category: 'Sports & Outdoors',
    image: '/products/yogamat.jpg',
    stock: 58,
    rating: 4.7,
    reviewCount: 499,
  },
  {
    id: 'prod_123',
    name: 'Running Shoes',
    description: 'High-quality running shoes with great features and excellent durability',
    price: 25.00,
    category: 'Sports & Outdoors',
    image: '/products/runningshoes.jpg',
    stock: 81,
    rating: 4.6,
    reviewCount: 343,
  },
  {
    id: 'prod_124',
    name: 'Hiking Backpack',
    description: 'High-quality hiking backpack with great features and excellent durability',
    price: 27.50,
    category: 'Sports & Outdoors',
    image: '/products/yogamat.jpg',
    stock: 101,
    rating: 4.3,
    reviewCount: 403,
  },
  {
    id: 'prod_125',
    name: 'Tent Camping',
    description: 'High-quality tent camping with great features and excellent durability',
    price: 30.00,
    category: 'Sports & Outdoors',
    image: '/products/dumbbells.jpg',
    stock: 52,
    rating: 4.2,
    reviewCount: 369,
  },
  {
    id: 'prod_126',
    name: 'Bicycle Mountain',
    description: 'High-quality bicycle mountain with great features and excellent durability',
    price: 32.50,
    category: 'Sports & Outdoors',
    image: '/products/bicycle.jpg',
    stock: 100,
    rating: 4.3,
    reviewCount: 161,
  },
  {
    id: 'prod_127',
    name: 'Skateboard Pro',
    description: 'High-quality skateboard pro with great features and excellent durability',
    price: 35.00,
    category: 'Sports & Outdoors',
    image: '/products/bicycle.jpg',
    stock: 95,
    rating: 4.2,
    reviewCount: 388,
  },
  {
    id: 'prod_128',
    name: 'Baseball Glove',
    description: 'High-quality baseball glove with great features and excellent durability',
    price: 37.50,
    category: 'Sports & Outdoors',
    image: '/products/dumbbells.jpg',
    stock: 112,
    rating: 4.5,
    reviewCount: 121,
  },
  {
    id: 'prod_129',
    name: 'Fishing Rod',
    description: 'High-quality fishing rod with great features and excellent durability',
    price: 40.00,
    category: 'Sports & Outdoors',
    image: '/products/bicycle.jpg',
    stock: 73,
    rating: 4.5,
    reviewCount: 232,
  },
  {
    id: 'prod_130',
    name: 'Golf Club Set',
    description: 'High-quality golf club set with great features and excellent durability',
    price: 42.50,
    category: 'Sports & Outdoors',
    image: '/products/racket.jpg',
    stock: 84,
    rating: 4.5,
    reviewCount: 118,
  },
  {
    id: 'prod_131',
    name: 'Tennis Racket',
    description: 'High-quality tennis racket with great features and excellent durability',
    price: 45.00,
    category: 'Sports & Outdoors',
    image: '/products/racket.jpg',
    stock: 116,
    rating: 4.1,
    reviewCount: 267,
  },
  {
    id: 'prod_132',
    name: 'Basketball',
    description: 'High-quality basketball with great features and excellent durability',
    price: 47.50,
    category: 'Sports & Outdoors',
    image: '/products/dumbbells.jpg',
    stock: 81,
    rating: 4.4,
    reviewCount: 132,
  },
  {
    id: 'prod_133',
    name: 'Soccer Ball',
    description: 'High-quality soccer ball with great features and excellent durability',
    price: 50.00,
    category: 'Sports & Outdoors',
    image: '/products/dumbbells.jpg',
    stock: 66,
    rating: 4.2,
    reviewCount: 286,
  },
  {
    id: 'prod_134',
    name: 'Resistance Bands',
    description: 'High-quality resistance bands with great features and excellent durability',
    price: 52.50,
    category: 'Sports & Outdoors',
    image: '/products/yogamat.jpg',
    stock: 103,
    rating: 4.5,
    reviewCount: 432,
  },
  {
    id: 'prod_135',
    name: 'Jump Rope',
    description: 'High-quality jump rope with great features and excellent durability',
    price: 55.00,
    category: 'Sports & Outdoors',
    image: '/products/dumbbells.jpg',
    stock: 45,
    rating: 4.7,
    reviewCount: 65,
  },
  {
    id: 'prod_136',
    name: 'Water Bottle',
    description: 'High-quality water bottle with great features and excellent durability',
    price: 57.50,
    category: 'Sports & Outdoors',
    image: '/products/glass.jpg',
    stock: 55,
    rating: 4.7,
    reviewCount: 454,
  },
  {
    id: 'prod_137',
    name: 'Sports Watch',
    description: 'High-quality sports watch with great features and excellent durability',
    price: 60.00,
    category: 'Sports & Outdoors',
    image: '/products/smartwatch.jpg',
    stock: 114,
    rating: 4.3,
    reviewCount: 438,
  },
  {
    id: 'prod_138',
    name: 'Gym Bag',
    description: 'High-quality gym bag with great features and excellent durability',
    price: 62.50,
    category: 'Sports & Outdoors',
    image: '/products/pillow.jpg',
    stock: 106,
    rating: 4.3,
    reviewCount: 270,
  },
  {
    id: 'prod_139',
    name: 'Swimming Goggles',
    description: 'High-quality swimming goggles with great features and excellent durability',
    price: 65.00,
    category: 'Sports & Outdoors',
    image: '/products/yogamat.jpg',
    stock: 32,
    rating: 4.7,
    reviewCount: 273,
  },
  {
    id: 'prod_140',
    name: 'Roller Skates',
    description: 'High-quality roller skates with great features and excellent durability',
    price: 67.50,
    category: 'Sports & Outdoors',
    image: '/products/sneakers.jpg',
    stock: 112,
    rating: 4.1,
    reviewCount: 240,
  },
  {
    id: 'prod_141',
    name: 'Climbing Rope',
    description: 'High-quality climbing rope with great features and excellent durability',
    price: 70.00,
    category: 'Sports & Outdoors',
    image: '/products/bicycle.jpg',
    stock: 87,
    rating: 4.3,
    reviewCount: 432,
  },
  {
    id: 'prod_142',
    name: 'Kite Flying',
    description: 'High-quality kite flying with great features and excellent durability',
    price: 72.50,
    category: 'Sports & Outdoors',
    image: '/products/dumbbells.jpg',
    stock: 69,
    rating: 4.3,
    reviewCount: 270,
  },
  {
    id: 'prod_143',
    name: 'Scooter Trick',
    description: 'High-quality scooter trick with great features and excellent durability',
    price: 75.00,
    category: 'Sports & Outdoors',
    image: '/products/bicycle.jpg',
    stock: 104,
    rating: 4.1,
    reviewCount: 435,
  },
  {
    id: 'prod_144',
    name: 'Handball',
    description: 'High-quality handball with great features and excellent durability',
    price: 77.50,
    category: 'Sports & Outdoors',
    image: '/products/dumbbells.jpg',
    stock: 54,
    rating: 4.6,
    reviewCount: 72,
  },
  {
    id: 'prod_145',
    name: 'Badminton Racket',
    description: 'High-quality badminton racket with great features and excellent durability',
    price: 80.00,
    category: 'Sports & Outdoors',
    image: '/products/racket.jpg',
    stock: 81,
    rating: 4.6,
    reviewCount: 421,
  },
  {
    id: 'prod_146',
    name: 'Cricket Bat',
    description: 'High-quality cricket bat with great features and excellent durability',
    price: 82.50,
    category: 'Sports & Outdoors',
    image: '/products/racket.jpg',
    stock: 93,
    rating: 4.6,
    reviewCount: 152,
  },
  {
    id: 'prod_147',
    name: 'Volleyball',
    description: 'High-quality volleyball with great features and excellent durability',
    price: 85.00,
    category: 'Sports & Outdoors',
    image: '/products/dumbbells.jpg',
    stock: 55,
    rating: 4.4,
    reviewCount: 314,
  },
  {
    id: 'prod_148',
    name: 'Inflatable Pool',
    description: 'High-quality inflatable pool with great features and excellent durability',
    price: 87.50,
    category: 'Sports & Outdoors',
    image: '/products/yogamat.jpg',
    stock: 86,
    rating: 4.8,
    reviewCount: 485,
  },
  {
    id: 'prod_149',
    name: 'Sleeping Bag',
    description: 'High-quality sleeping bag with great features and excellent durability',
    price: 90.00,
    category: 'Sports & Outdoors',
    image: '/products/bedding.jpg',
    stock: 25,
    rating: 4.1,
    reviewCount: 402,
  },
  {
    id: 'prod_150',
    name: 'Kayak Paddle',
    description: 'High-quality kayak paddle with great features and excellent durability',
    price: 92.50,
    category: 'Sports & Outdoors',
    image: '/products/bicycle.jpg',
    stock: 55,
    rating: 4.7,
    reviewCount: 71,
  },
  {
    id: 'prod_151',
    name: 'Colorful Building Blocks Set',
    description: 'High-quality colorful building blocks set with great features and excellent durability',
    price: 20.00,
    category: 'Toys & Games',
    image: '/products/blocks.jpg',
    stock: 73,
    rating: 4.2,
    reviewCount: 364,
  },
  {
    id: 'prod_152',
    name: 'Fashion Doll with Accessories',
    description: 'High-quality fashion doll with accessories with great features and excellent durability',
    price: 22.50,
    category: 'Toys & Games',
    image: '/products/doll.jpg',
    stock: 94,
    rating: 4.4,
    reviewCount: 266,
  },
  {
    id: 'prod_153',
    name: 'Board Game Strategy',
    description: 'High-quality board game strategy with great features and excellent durability',
    price: 25.00,
    category: 'Toys & Games',
    image: '/products/boardgame.jpg',
    stock: 103,
    rating: 4.3,
    reviewCount: 404,
  },
  {
    id: 'prod_154',
    name: 'Puzzle 1000 Pieces',
    description: 'High-quality puzzle 1000 pieces with great features and excellent durability',
    price: 27.50,
    category: 'Toys & Games',
    image: '/products/puzzle.jpg',
    stock: 57,
    rating: 4.6,
    reviewCount: 253,
  },
  {
    id: 'prod_155',
    name: 'Action Figure',
    description: 'High-quality action figure with great features and excellent durability',
    price: 30.00,
    category: 'Toys & Games',
    image: '/products/doll.jpg',
    stock: 93,
    rating: 4.3,
    reviewCount: 301,
  },
  {
    id: 'prod_156',
    name: 'Remote Control Car',
    description: 'High-quality remote control car with great features and excellent durability',
    price: 32.50,
    category: 'Toys & Games',
    image: '/products/blocks.jpg',
    stock: 34,
    rating: 4.5,
    reviewCount: 213,
  },
  {
    id: 'prod_157',
    name: 'Board Game Family',
    description: 'High-quality board game family with great features and excellent durability',
    price: 35.00,
    category: 'Toys & Games',
    image: '/products/boardgame.jpg',
    stock: 109,
    rating: 4.5,
    reviewCount: 325,
  },
  {
    id: 'prod_158',
    name: 'Card Game Set',
    description: 'High-quality card game set with great features and excellent durability',
    price: 37.50,
    category: 'Toys & Games',
    image: '/products/boardgame.jpg',
    stock: 74,
    rating: 4.5,
    reviewCount: 327,
  },
  {
    id: 'prod_159',
    name: 'LEGO Set',
    description: 'High-quality lego set with great features and excellent durability',
    price: 40.00,
    category: 'Toys & Games',
    image: '/products/blocks.jpg',
    stock: 102,
    rating: 4.1,
    reviewCount: 310,
  },
  {
    id: 'prod_160',
    name: 'Toy Train',
    description: 'High-quality toy train with great features and excellent durability',
    price: 42.50,
    category: 'Toys & Games',
    image: '/products/blocks.jpg',
    stock: 33,
    rating: 4.1,
    reviewCount: 194,
  },
  {
    id: 'prod_161',
    name: 'Doll House',
    description: 'High-quality doll house with great features and excellent durability',
    price: 45.00,
    category: 'Toys & Games',
    image: '/products/doll.jpg',
    stock: 62,
    rating: 4.6,
    reviewCount: 114,
  },
  {
    id: 'prod_162',
    name: 'Board Game Classic',
    description: 'High-quality board game classic with great features and excellent durability',
    price: 47.50,
    category: 'Toys & Games',
    image: '/products/boardgame.jpg',
    stock: 34,
    rating: 4.5,
    reviewCount: 395,
  },
  {
    id: 'prod_163',
    name: 'Puzzle 500 Pieces',
    description: 'High-quality puzzle 500 pieces with great features and excellent durability',
    price: 50.00,
    category: 'Toys & Games',
    image: '/products/puzzle.jpg',
    stock: 83,
    rating: 4.4,
    reviewCount: 212,
  },
  {
    id: 'prod_164',
    name: 'Video Game Console',
    description: 'High-quality video game console with great features and excellent durability',
    price: 52.50,
    category: 'Toys & Games',
    image: '/products/boardgame.jpg',
    stock: 61,
    rating: 4.4,
    reviewCount: 409,
  },
  {
    id: 'prod_165',
    name: 'Toy Robot',
    description: 'High-quality toy robot with great features and excellent durability',
    price: 55.00,
    category: 'Toys & Games',
    image: '/products/blocks.jpg',
    stock: 31,
    rating: 4.4,
    reviewCount: 74,
  },
  {
    id: 'prod_166',
    name: 'Escape Room Game',
    description: 'High-quality escape room game with great features and excellent durability',
    price: 57.50,
    category: 'Toys & Games',
    image: '/products/boardgame.jpg',
    stock: 56,
    rating: 4.2,
    reviewCount: 95,
  },
  {
    id: 'prod_167',
    name: 'Dice Game',
    description: 'High-quality dice game with great features and excellent durability',
    price: 60.00,
    category: 'Toys & Games',
    image: '/products/boardgame.jpg',
    stock: 57,
    rating: 4.2,
    reviewCount: 465,
  },
  {
    id: 'prod_168',
    name: 'Collectible Figure',
    description: 'High-quality collectible figure with great features and excellent durability',
    price: 62.50,
    category: 'Toys & Games',
    image: '/products/doll.jpg',
    stock: 109,
    rating: 4.4,
    reviewCount: 327,
  },
  {
    id: 'prod_169',
    name: 'Model Building',
    description: 'High-quality model building with great features and excellent durability',
    price: 65.00,
    category: 'Toys & Games',
    image: '/products/blocks.jpg',
    stock: 70,
    rating: 4.1,
    reviewCount: 279,
  },
  {
    id: 'prod_170',
    name: 'Toy Soldier Set',
    description: 'High-quality toy soldier set with great features and excellent durability',
    price: 67.50,
    category: 'Toys & Games',
    image: '/products/doll.jpg',
    stock: 118,
    rating: 4.6,
    reviewCount: 84,
  },
  {
    id: 'prod_171',
    name: 'Memory Card Game',
    description: 'High-quality memory card game with great features and excellent durability',
    price: 70.00,
    category: 'Toys & Games',
    image: '/products/boardgame.jpg',
    stock: 98,
    rating: 4.3,
    reviewCount: 499,
  },
  {
    id: 'prod_172',
    name: 'Trivia Game',
    description: 'High-quality trivia game with great features and excellent durability',
    price: 72.50,
    category: 'Toys & Games',
    image: '/products/boardgame.jpg',
    stock: 99,
    rating: 4.6,
    reviewCount: 79,
  },
  {
    id: 'prod_173',
    name: 'Charades Game',
    description: 'High-quality charades game with great features and excellent durability',
    price: 75.00,
    category: 'Toys & Games',
    image: '/products/boardgame.jpg',
    stock: 23,
    rating: 4.5,
    reviewCount: 418,
  },
  {
    id: 'prod_174',
    name: 'Trading Card',
    description: 'High-quality trading card with great features and excellent durability',
    price: 77.50,
    category: 'Toys & Games',
    image: '/products/boardgame.jpg',
    stock: 88,
    rating: 4.4,
    reviewCount: 452,
  },
  {
    id: 'prod_175',
    name: 'Spin Game',
    description: 'High-quality spin game with great features and excellent durability',
    price: 80.00,
    category: 'Toys & Games',
    image: '/products/boardgame.jpg',
    stock: 98,
    rating: 4.0,
    reviewCount: 314,
  },
  {
    id: 'prod_176',
    name: 'Marble Game',
    description: 'High-quality marble game with great features and excellent durability',
    price: 82.50,
    category: 'Toys & Games',
    image: '/products/blocks.jpg',
    stock: 25,
    rating: 4.1,
    reviewCount: 322,
  },
  {
    id: 'prod_177',
    name: 'Domino Set',
    description: 'High-quality domino set with great features and excellent durability',
    price: 85.00,
    category: 'Toys & Games',
    image: '/products/boardgame.jpg',
    stock: 102,
    rating: 4.7,
    reviewCount: 284,
  },
  {
    id: 'prod_178',
    name: 'Wooden Puzzle',
    description: 'High-quality wooden puzzle with great features and excellent durability',
    price: 87.50,
    category: 'Toys & Games',
    image: '/products/puzzle.jpg',
    stock: 35,
    rating: 4.2,
    reviewCount: 416,
  },
  {
    id: 'prod_179',
    name: 'Crystal Growing',
    description: 'High-quality crystal growing with great features and excellent durability',
    price: 90.00,
    category: 'Toys & Games',
    image: '/products/blocks.jpg',
    stock: 100,
    rating: 4.5,
    reviewCount: 431,
  },
  {
    id: 'prod_180',
    name: 'Magic Trick Kit',
    description: 'High-quality magic trick kit with great features and excellent durability',
    price: 92.50,
    category: 'Toys & Games',
    image: '/products/boardgame.jpg',
    stock: 22,
    rating: 4.5,
    reviewCount: 337,
  },
  {
    id: 'prod_181',
    name: 'Skincare Cream Set',
    description: 'High-quality skincare cream set with great features and excellent durability',
    price: 20.00,
    category: 'Beauty & Personal Care',
    image: '/products/skincare.jpg',
    stock: 27,
    rating: 4.6,
    reviewCount: 213,
  },
  {
    id: 'prod_182',
    name: 'Red Lipstick',
    description: 'High-quality red lipstick with great features and excellent durability',
    price: 22.50,
    category: 'Beauty & Personal Care',
    image: '/products/lipstick.jpg',
    stock: 89,
    rating: 4.5,
    reviewCount: 497,
  },
  {
    id: 'prod_183',
    name: 'Designer Perfume',
    description: 'High-quality designer perfume with great features and excellent durability',
    price: 25.00,
    category: 'Beauty & Personal Care',
    image: '/products/perfume.jpg',
    stock: 92,
    rating: 4.8,
    reviewCount: 300,
  },
  {
    id: 'prod_184',
    name: 'Face Wash Cleanser',
    description: 'High-quality face wash cleanser with great features and excellent durability',
    price: 27.50,
    category: 'Beauty & Personal Care',
    image: '/products/skincare.jpg',
    stock: 99,
    rating: 4.2,
    reviewCount: 435,
  },
  {
    id: 'prod_185',
    name: 'Hair Shampoo',
    description: 'High-quality hair shampoo with great features and excellent durability',
    price: 30.00,
    category: 'Beauty & Personal Care',
    image: '/products/shampoo.jpg',
    stock: 117,
    rating: 4.6,
    reviewCount: 418,
  },
  {
    id: 'prod_186',
    name: 'Hair Conditioner',
    description: 'High-quality hair conditioner with great features and excellent durability',
    price: 32.50,
    category: 'Beauty & Personal Care',
    image: '/products/shampoo.jpg',
    stock: 75,
    rating: 4.3,
    reviewCount: 219,
  },
  {
    id: 'prod_187',
    name: 'Body Lotion',
    description: 'High-quality body lotion with great features and excellent durability',
    price: 35.00,
    category: 'Beauty & Personal Care',
    image: '/products/skincare.jpg',
    stock: 25,
    rating: 4.6,
    reviewCount: 186,
  },
  {
    id: 'prod_188',
    name: 'Face Serum',
    description: 'High-quality face serum with great features and excellent durability',
    price: 37.50,
    category: 'Beauty & Personal Care',
    image: '/products/skincare.jpg',
    stock: 113,
    rating: 4.1,
    reviewCount: 125,
  },
  {
    id: 'prod_189',
    name: 'Eye Cream',
    description: 'High-quality eye cream with great features and excellent durability',
    price: 40.00,
    category: 'Beauty & Personal Care',
    image: '/products/skincare.jpg',
    stock: 27,
    rating: 4.6,
    reviewCount: 452,
  },
  {
    id: 'prod_190',
    name: 'Lip Balm',
    description: 'High-quality lip balm with great features and excellent durability',
    price: 42.50,
    category: 'Beauty & Personal Care',
    image: '/products/lipstick.jpg',
    stock: 68,
    rating: 4.4,
    reviewCount: 483,
  },
  {
    id: 'prod_191',
    name: 'Toothbrush Electric',
    description: 'High-quality toothbrush electric with great features and excellent durability',
    price: 45.00,
    category: 'Beauty & Personal Care',
    image: '/products/deodorant.jpg',
    stock: 92,
    rating: 4.6,
    reviewCount: 478,
  },
  {
    id: 'prod_192',
    name: 'Deodorant',
    description: 'High-quality deodorant with great features and excellent durability',
    price: 47.50,
    category: 'Beauty & Personal Care',
    image: '/products/deodorant.jpg',
    stock: 102,
    rating: 4.3,
    reviewCount: 481,
  },
  {
    id: 'prod_193',
    name: 'Bath Soap',
    description: 'High-quality bath soap with great features and excellent durability',
    price: 50.00,
    category: 'Beauty & Personal Care',
    image: '/products/skincare.jpg',
    stock: 116,
    rating: 4.0,
    reviewCount: 153,
  },
  {
    id: 'prod_194',
    name: 'Face Mask',
    description: 'High-quality face mask with great features and excellent durability',
    price: 52.50,
    category: 'Beauty & Personal Care',
    image: '/products/skincare.jpg',
    stock: 70,
    rating: 4.6,
    reviewCount: 127,
  },
  {
    id: 'prod_195',
    name: 'Nail Polish',
    description: 'High-quality nail polish with great features and excellent durability',
    price: 55.00,
    category: 'Beauty & Personal Care',
    image: '/products/lipstick.jpg',
    stock: 82,
    rating: 4.6,
    reviewCount: 183,
  },
  {
    id: 'prod_196',
    name: 'Hairbrush',
    description: 'High-quality hairbrush with great features and excellent durability',
    price: 57.50,
    category: 'Beauty & Personal Care',
    image: '/products/makeup.jpg',
    stock: 113,
    rating: 4.6,
    reviewCount: 483,
  },
  {
    id: 'prod_197',
    name: 'Hair Comb',
    description: 'High-quality hair comb with great features and excellent durability',
    price: 60.00,
    category: 'Beauty & Personal Care',
    image: '/products/makeup.jpg',
    stock: 61,
    rating: 4.1,
    reviewCount: 367,
  },
  {
    id: 'prod_198',
    name: 'Makeup Brush Set',
    description: 'High-quality makeup brush set with great features and excellent durability',
    price: 62.50,
    category: 'Beauty & Personal Care',
    image: '/products/makeup.jpg',
    stock: 58,
    rating: 4.3,
    reviewCount: 149,
  },
  {
    id: 'prod_199',
    name: 'Concealer',
    description: 'High-quality concealer with great features and excellent durability',
    price: 65.00,
    category: 'Beauty & Personal Care',
    image: '/products/lipstick.jpg',
    stock: 43,
    rating: 4.2,
    reviewCount: 70,
  },
  {
    id: 'prod_200',
    name: 'Foundation',
    description: 'High-quality foundation with great features and excellent durability',
    price: 67.50,
    category: 'Beauty & Personal Care',
    image: '/products/skincare.jpg',
    stock: 50,
    rating: 4.8,
    reviewCount: 141,
  },
  {
    id: 'prod_201',
    name: 'Blush Powder',
    description: 'High-quality blush powder with great features and excellent durability',
    price: 70.00,
    category: 'Beauty & Personal Care',
    image: '/products/lipstick.jpg',
    stock: 78,
    rating: 4.6,
    reviewCount: 226,
  },
  {
    id: 'prod_202',
    name: 'Eye Shadow',
    description: 'High-quality eye shadow with great features and excellent durability',
    price: 72.50,
    category: 'Beauty & Personal Care',
    image: '/products/lipstick.jpg',
    stock: 92,
    rating: 4.3,
    reviewCount: 426,
  },
  {
    id: 'prod_203',
    name: 'Eyeliner',
    description: 'High-quality eyeliner with great features and excellent durability',
    price: 75.00,
    category: 'Beauty & Personal Care',
    image: '/products/lipstick.jpg',
    stock: 57,
    rating: 4.5,
    reviewCount: 324,
  },
  {
    id: 'prod_204',
    name: 'Mascara',
    description: 'High-quality mascara with great features and excellent durability',
    price: 77.50,
    category: 'Beauty & Personal Care',
    image: '/products/lipstick.jpg',
    stock: 68,
    rating: 4.1,
    reviewCount: 340,
  },
  {
    id: 'prod_205',
    name: 'Face Cleanser Foam',
    description: 'High-quality face cleanser foam with great features and excellent durability',
    price: 80.00,
    category: 'Beauty & Personal Care',
    image: '/products/skincare.jpg',
    stock: 50,
    rating: 4.5,
    reviewCount: 116,
  },
  {
    id: 'prod_206',
    name: 'Night Cream',
    description: 'High-quality night cream with great features and excellent durability',
    price: 82.50,
    category: 'Beauty & Personal Care',
    image: '/products/skincare.jpg',
    stock: 80,
    rating: 4.7,
    reviewCount: 222,
  },
  {
    id: 'prod_207',
    name: 'Sunscreen SPF',
    description: 'High-quality sunscreen spf with great features and excellent durability',
    price: 85.00,
    category: 'Beauty & Personal Care',
    image: '/products/skincare.jpg',
    stock: 77,
    rating: 4.4,
    reviewCount: 262,
  },
  {
    id: 'prod_208',
    name: 'Moisturizer Gel',
    description: 'High-quality moisturizer gel with great features and excellent durability',
    price: 87.50,
    category: 'Beauty & Personal Care',
    image: '/products/skincare.jpg',
    stock: 98,
    rating: 4.7,
    reviewCount: 296,
  },
  {
    id: 'prod_209',
    name: 'Face Toner',
    description: 'High-quality face toner with great features and excellent durability',
    price: 90.00,
    category: 'Beauty & Personal Care',
    image: '/products/skincare.jpg',
    stock: 60,
    rating: 4.0,
    reviewCount: 266,
  },
  {
    id: 'prod_210',
    name: 'Hair Oil',
    description: 'High-quality hair oil with great features and excellent durability',
    price: 92.50,
    category: 'Beauty & Personal Care',
    image: '/products/shampoo.jpg',
    stock: 87,
    rating: 4.6,
    reviewCount: 496,
  },
  {
    id: 'prod_211',
    name: 'Coffee Maker Machine',
    description: 'High-quality coffee maker machine with great features and excellent durability',
    price: 20.00,
    category: 'Kitchen & Dining',
    image: '/products/coffeemachine.jpg',
    stock: 43,
    rating: 4.0,
    reviewCount: 478,
  },
  {
    id: 'prod_212',
    name: 'Stainless Steel Blender',
    description: 'High-quality stainless steel blender with great features and excellent durability',
    price: 22.50,
    category: 'Kitchen & Dining',
    image: '/products/blender.jpg',
    stock: 50,
    rating: 4.1,
    reviewCount: 355,
  },
  {
    id: 'prod_213',
    name: 'Non-Stick Pan',
    description: 'High-quality non-stick pan with great features and excellent durability',
    price: 25.00,
    category: 'Kitchen & Dining',
    image: '/products/cookware.jpg',
    stock: 69,
    rating: 4.8,
    reviewCount: 206,
  },
  {
    id: 'prod_214',
    name: 'Cutting Board',
    description: 'High-quality cutting board with great features and excellent durability',
    price: 27.50,
    category: 'Kitchen & Dining',
    image: '/products/knife.jpg',
    stock: 57,
    rating: 4.5,
    reviewCount: 185,
  },
  {
    id: 'prod_215',
    name: 'Chef Knife',
    description: 'High-quality chef knife with great features and excellent durability',
    price: 30.00,
    category: 'Kitchen & Dining',
    image: '/products/knife.jpg',
    stock: 60,
    rating: 4.8,
    reviewCount: 433,
  },
  {
    id: 'prod_216',
    name: 'Cooking Pot',
    description: 'High-quality cooking pot with great features and excellent durability',
    price: 32.50,
    category: 'Kitchen & Dining',
    image: '/products/cookware.jpg',
    stock: 58,
    rating: 4.5,
    reviewCount: 215,
  },
  {
    id: 'prod_217',
    name: 'Baking Sheet',
    description: 'High-quality baking sheet with great features and excellent durability',
    price: 35.00,
    category: 'Kitchen & Dining',
    image: '/products/cookware.jpg',
    stock: 94,
    rating: 4.6,
    reviewCount: 294,
  },
  {
    id: 'prod_218',
    name: 'Mixing Bowls',
    description: 'High-quality mixing bowls with great features and excellent durability',
    price: 37.50,
    category: 'Kitchen & Dining',
    image: '/products/blender.jpg',
    stock: 71,
    rating: 4.8,
    reviewCount: 422,
  },
  {
    id: 'prod_219',
    name: 'Measuring Cups',
    description: 'High-quality measuring cups with great features and excellent durability',
    price: 40.00,
    category: 'Kitchen & Dining',
    image: '/products/dinnerware.jpg',
    stock: 87,
    rating: 4.7,
    reviewCount: 474,
  },
  {
    id: 'prod_220',
    name: 'Spatula Set',
    description: 'High-quality spatula set with great features and excellent durability',
    price: 42.50,
    category: 'Kitchen & Dining',
    image: '/products/knife.jpg',
    stock: 46,
    rating: 4.5,
    reviewCount: 354,
  },
  {
    id: 'prod_221',
    name: 'Whisk',
    description: 'High-quality whisk with great features and excellent durability',
    price: 45.00,
    category: 'Kitchen & Dining',
    image: '/products/knife.jpg',
    stock: 117,
    rating: 4.7,
    reviewCount: 292,
  },
  {
    id: 'prod_222',
    name: 'Tongs',
    description: 'High-quality tongs with great features and excellent durability',
    price: 47.50,
    category: 'Kitchen & Dining',
    image: '/products/knife.jpg',
    stock: 45,
    rating: 4.3,
    reviewCount: 486,
  },
  {
    id: 'prod_223',
    name: 'Can Opener',
    description: 'High-quality can opener with great features and excellent durability',
    price: 50.00,
    category: 'Kitchen & Dining',
    image: '/products/knife.jpg',
    stock: 29,
    rating: 4.5,
    reviewCount: 114,
  },
  {
    id: 'prod_224',
    name: 'Grater',
    description: 'High-quality grater with great features and excellent durability',
    price: 52.50,
    category: 'Kitchen & Dining',
    image: '/products/knife.jpg',
    stock: 26,
    rating: 4.6,
    reviewCount: 237,
  },
  {
    id: 'prod_225',
    name: 'Rolling Pin',
    description: 'High-quality rolling pin with great features and excellent durability',
    price: 55.00,
    category: 'Kitchen & Dining',
    image: '/products/knife.jpg',
    stock: 108,
    rating: 4.1,
    reviewCount: 184,
  },
  {
    id: 'prod_226',
    name: 'Colander',
    description: 'High-quality colander with great features and excellent durability',
    price: 57.50,
    category: 'Kitchen & Dining',
    image: '/products/blender.jpg',
    stock: 75,
    rating: 4.7,
    reviewCount: 209,
  },
  {
    id: 'prod_227',
    name: 'Strainer',
    description: 'High-quality strainer with great features and excellent durability',
    price: 60.00,
    category: 'Kitchen & Dining',
    image: '/products/blender.jpg',
    stock: 51,
    rating: 4.6,
    reviewCount: 433,
  },
  {
    id: 'prod_228',
    name: 'Ladle',
    description: 'High-quality ladle with great features and excellent durability',
    price: 62.50,
    category: 'Kitchen & Dining',
    image: '/products/knife.jpg',
    stock: 110,
    rating: 4.5,
    reviewCount: 415,
  },
  {
    id: 'prod_229',
    name: 'Wooden Spoon',
    description: 'High-quality wooden spoon with great features and excellent durability',
    price: 65.00,
    category: 'Kitchen & Dining',
    image: '/products/knife.jpg',
    stock: 107,
    rating: 4.1,
    reviewCount: 246,
  },
  {
    id: 'prod_230',
    name: 'Dinner Plate Set',
    description: 'High-quality dinner plate set with great features and excellent durability',
    price: 67.50,
    category: 'Kitchen & Dining',
    image: '/products/dinnerware.jpg',
    stock: 23,
    rating: 4.5,
    reviewCount: 315,
  },
  {
    id: 'prod_231',
    name: 'Drinking Glass Set',
    description: 'High-quality drinking glass set with great features and excellent durability',
    price: 70.00,
    category: 'Kitchen & Dining',
    image: '/products/glass.jpg',
    stock: 62,
    rating: 4.7,
    reviewCount: 231,
  },
  {
    id: 'prod_232',
    name: 'Mug Coffee',
    description: 'High-quality mug coffee with great features and excellent durability',
    price: 72.50,
    category: 'Kitchen & Dining',
    image: '/products/coffeemachine.jpg',
    stock: 72,
    rating: 4.0,
    reviewCount: 259,
  },
  {
    id: 'prod_233',
    name: 'Salad Bowl',
    description: 'High-quality salad bowl with great features and excellent durability',
    price: 75.00,
    category: 'Kitchen & Dining',
    image: '/products/blender.jpg',
    stock: 76,
    rating: 4.4,
    reviewCount: 435,
  },
  {
    id: 'prod_234',
    name: 'Serving Platter',
    description: 'High-quality serving platter with great features and excellent durability',
    price: 77.50,
    category: 'Kitchen & Dining',
    image: '/products/dinnerware.jpg',
    stock: 89,
    rating: 4.6,
    reviewCount: 269,
  },
  {
    id: 'prod_235',
    name: 'Napkins Cloth',
    description: 'High-quality napkins cloth with great features and excellent durability',
    price: 80.00,
    category: 'Kitchen & Dining',
    image: '/products/dinnerware.jpg',
    stock: 25,
    rating: 4.5,
    reviewCount: 203,
  },
  {
    id: 'prod_236',
    name: 'Tablecloth',
    description: 'High-quality tablecloth with great features and excellent durability',
    price: 82.50,
    category: 'Kitchen & Dining',
    image: '/products/dinnerware.jpg',
    stock: 92,
    rating: 4.2,
    reviewCount: 331,
  },
  {
    id: 'prod_237',
    name: 'Apron',
    description: 'High-quality apron with great features and excellent durability',
    price: 85.00,
    category: 'Kitchen & Dining',
    image: '/products/dinnerware.jpg',
    stock: 89,
    rating: 4.3,
    reviewCount: 373,
  },
  {
    id: 'prod_238',
    name: 'Oven Mitt',
    description: 'High-quality oven mitt with great features and excellent durability',
    price: 87.50,
    category: 'Kitchen & Dining',
    image: '/products/cookware.jpg',
    stock: 42,
    rating: 4.1,
    reviewCount: 304,
  },
  {
    id: 'prod_239',
    name: 'Pot Holder',
    description: 'High-quality pot holder with great features and excellent durability',
    price: 90.00,
    category: 'Kitchen & Dining',
    image: '/products/cookware.jpg',
    stock: 38,
    rating: 4.2,
    reviewCount: 327,
  },
  {
    id: 'prod_240',
    name: 'Food Storage Container',
    description: 'High-quality food storage container with great features and excellent durability',
    price: 92.50,
    category: 'Kitchen & Dining',
    image: '/products/blender.jpg',
    stock: 107,
    rating: 4.2,
    reviewCount: 131,
  },
];
